source 'https://cdn.cocoapods.org/'

platform :ios, '11'
inhibit_all_warnings!

install! 'cocoapods', :disable_input_output_paths => true, :deterministic_uuids => false

target 'GTCompanion' do
    use_frameworks!
    pod 'MultiPlatformLibrary', :path => '../mpp-library/'
end
