source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
inhibit_all_warnings!

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

target 'GTCompanion' do
  use_frameworks!

  # MultiPlatformLibrary
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
  pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.4.0'

  target 'GTCompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GTCompanionUITests' do
    # Pods for testing
  end
end
